baseURL = 'http://journal.rabinacharya.info.np/'
languageCode = 'en-us'
title = "Rabin's Daily Journal"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10
